apiVersion: v1
kind: Secret
metadata:
  name: quick-fastapi-medium-secret
type: Opaque
stringData:
  SECRET_KEY: "change-me-in-production"
  DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres.default.svc.cluster.local:5432/quick_fastapi_medium"
