apiVersion: v1
kind: Secret
metadata:
  name: quick-fastapi-medium-secret
type: Opaque
stringData:
  SECRET_KEY: "change-me-in-production"
  DATABASE_URL: "postgresql+psycopg://postgres:postgres@quick-fastapi-medium-postgres:5432/quick_fastapi_medium"
  POSTGRES_DB: "quick_fastapi_medium"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
