resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: quick-fastapi-medium
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quick-fastapi-medium:dev
